version: '3.9'

services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: devops_db
    ports:
      - "5432:5432"